using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;

namespace DiceForge.Conformance
{
    /// <summary>
    /// Runs the core conformance vectors against the C# port (ADR-0021).
    ///
    /// The vectors are generated by the TypeScript core and committed at
    /// packages/testing/vectors/core-vectors.json; this runner must reproduce
    /// every number, normalized string, error position and record in them, bit
    /// for bit. Exit code 0 when everything matches, 1 otherwise, so CI can
    /// gate on it exactly like the Godot conformance scene does.
    ///
    /// A console app rather than a test framework, deliberately: it needs no
    /// NuGet restore, runs offline, and mirrors the Godot runner's shape.
    /// </summary>
    public static class Program
    {
        private static int _checks;
        private static int _failures;
        private static readonly List<string> Report = new List<string>();

        public static int Main(string[] args)
        {
            string path = args.Length > 0 ? Path.GetFullPath(args[0]) : FindVectors();
            if (path == null || !File.Exists(path))
            {
                Console.Error.WriteLine(
                    "cannot find packages/testing/vectors/core-vectors.json; pass its path as an argument");
                return 1;
            }

            using JsonDocument document = JsonDocument.Parse(File.ReadAllText(path));
            JsonElement vectors = document.RootElement;

            RunRng(vectors.GetProperty("rng"));
            RunFaces(vectors.GetProperty("faces"));
            RunParse(vectors.GetProperty("parse"), vectors.GetProperty("rolls"));
            RunParseErrors(vectors.GetProperty("parseErrors"), vectors.GetProperty("rolls"));
            RunRolls(vectors.GetProperty("rolls"));
            RunCoins(vectors.GetProperty("coins"));

            string summary = string.Format(
                "CONFORMANCE {0}: {1} checks, {2} failures",
                _failures == 0 ? "PASS" : "FAIL",
                _checks,
                _failures);
            Console.WriteLine(summary);
            Report.Add(summary);
            File.WriteAllText(
                Path.Combine(AppContext.BaseDirectory, "conformance-report.txt"),
                string.Join("\n", Report) + "\n");
            return _failures == 0 ? 0 : 1;
        }

        /// <summary>
        /// Walks up from the built binary looking for the committed vectors, so
        /// the runner does not care how deep the output directory happens to be
        /// or where it was launched from.
        /// </summary>
        private static string FindVectors()
        {
            const string relative = "packages/testing/vectors/core-vectors.json";
            var directory = new DirectoryInfo(AppContext.BaseDirectory);
            while (directory != null)
            {
                string candidate = Path.Combine(directory.FullName, relative);
                if (File.Exists(candidate)) return Path.GetFullPath(candidate);
                directory = directory.Parent;
            }
            return null;
        }

        private static void Check(bool ok, string label, object expected, object got)
        {
            _checks++;
            if (ok) return;
            _failures++;
            string message = "FAIL " + label;
            Console.Error.WriteLine(message);
            Console.Error.WriteLine("  expected: " + expected);
            Console.Error.WriteLine("  got:      " + got);
            Report.Add(message);
            Report.Add("  expected: " + expected);
            Report.Add("  got:      " + got);
        }

        /// <summary>Seeded streams: the contract every other vector rests on.</summary>
        private static void RunRng(JsonElement vectors)
        {
            foreach (JsonElement vector in vectors.EnumerateArray())
            {
                string seed = vector.GetProperty("seed").GetString();
                JsonElement expected = vector.GetProperty("uint32");
                var source = SeededRandom.Create(seed);
                var got = new List<uint>();
                foreach (JsonElement _ in expected.EnumerateArray())
                {
                    got.Add(source.NextUint32());
                }
                bool ok = true;
                int index = 0;
                foreach (JsonElement value in expected.EnumerateArray())
                {
                    if (value.GetUInt32() != got[index]) ok = false;
                    index++;
                }
                Check(
                    ok,
                    "rng seed " + JsonSerializer.Serialize(seed),
                    JsonSerializer.Serialize(expected),
                    JsonSerializer.Serialize(got));
            }
        }

        /// <summary>
        /// Face sampling. RollFace is internal to the contract, so this asks
        /// from the outside: a one-die group with no modifiers consumes exactly
        /// one draw per die, which is the same statement.
        /// </summary>
        private static void RunFaces(JsonElement vectors)
        {
            foreach (JsonElement vector in vectors.EnumerateArray())
            {
                string seed = vector.GetProperty("seed").GetString();
                int sides = vector.GetProperty("sides").GetInt32();
                var forge = DiceForgeEngine.Seeded(seed);
                var got = new List<int>();
                var expected = new List<int>();
                foreach (JsonElement value in vector.GetProperty("values").EnumerateArray())
                {
                    expected.Add(value.GetInt32());
                    got.Add(forge.Roll("1d" + sides).Groups[0].Dice[0].Value);
                }
                Check(
                    expected.SequenceEqual(got),
                    "faces seed " + seed + " d" + sides,
                    string.Join(",", expected),
                    string.Join(",", got));
            }
        }

        /// <summary>
        /// The registry the vectors were generated with — the fate die from the
        /// roll vectors, which is the only one they define.
        /// </summary>
        private static DieRegistry FateRegistry(JsonElement rolls)
        {
            foreach (JsonElement vector in rolls.EnumerateArray())
            {
                if (!vector.TryGetProperty("dice", out JsonElement dice)) continue;
                return new DieRegistry(ReadDice(dice));
            }
            return new DieRegistry();
        }

        private static List<DieDefinition> ReadDice(JsonElement dice)
        {
            var defined = new List<DieDefinition>();
            foreach (JsonElement definition in dice.EnumerateArray())
            {
                var faces = new List<DieFace>();
                foreach (JsonElement face in definition.GetProperty("faces").EnumerateArray())
                {
                    string label = face.TryGetProperty("label", out JsonElement l) ? l.GetString() : null;
                    faces.Add(new DieFace(face.GetProperty("value").GetInt32(), label));
                }
                defined.Add(DieDefinition.Define(definition.GetProperty("id").GetString(), faces));
            }
            return defined;
        }

        private static void RunParse(JsonElement vectors, JsonElement rolls)
        {
            DieRegistry registry = FateRegistry(rolls);
            foreach (JsonElement vector in vectors.EnumerateArray())
            {
                string expression = vector.GetProperty("expression").GetString();
                string expected = vector.GetProperty("normalized").GetString();
                string got;
                try
                {
                    got = Notation.Parse(expression, registry).Normalized;
                }
                catch (DiceForgeException error)
                {
                    got = "threw: " + error.Message;
                }
                Check(got == expected, "parse " + JsonSerializer.Serialize(expression), expected, got);
            }
        }

        /// <summary>
        /// Error positions are API; wording is not (ADR-0021). Only the
        /// position is compared.
        /// </summary>
        private static void RunParseErrors(JsonElement vectors, JsonElement rolls)
        {
            DieRegistry registry = FateRegistry(rolls);
            foreach (JsonElement vector in vectors.EnumerateArray())
            {
                string expression = vector.GetProperty("expression").GetString();
                int expected = vector.GetProperty("position").GetInt32();
                object got;
                try
                {
                    Notation.Parse(expression, registry);
                    got = "parsed fine";
                }
                catch (DiceNotationException error)
                {
                    got = error.Position;
                }
                Check(
                    got is int position && position == expected,
                    "parse error " + JsonSerializer.Serialize(expression),
                    expected,
                    got);
            }
        }

        /// <summary>Whole resolved records, compared field by field.</summary>
        private static void RunRolls(JsonElement vectors)
        {
            foreach (JsonElement vector in vectors.EnumerateArray())
            {
                string seed = vector.GetProperty("seed").GetString();
                string expression = vector.GetProperty("expression").GetString();
                var forge = DiceForgeEngine.Seeded(seed);
                if (vector.TryGetProperty("dice", out JsonElement dice))
                {
                    foreach (DieDefinition definition in ReadDice(dice))
                    {
                        forge.DefineDie(definition.Id, definition.Faces);
                    }
                }
                string got = forge.Roll(expression).ToJson();
                JsonElement expected = vector.GetProperty("record");
                using JsonDocument produced = JsonDocument.Parse(got);
                Check(
                    DeepEqual(expected, produced.RootElement),
                    "roll " + JsonSerializer.Serialize(expression) + " seed " + seed,
                    JsonSerializer.Serialize(expected),
                    got);
            }
        }

        private static void RunCoins(JsonElement vectors)
        {
            foreach (JsonElement vector in vectors.EnumerateArray())
            {
                string seed = vector.GetProperty("seed").GetString();
                var forge = DiceForgeEngine.Seeded(seed);
                var got = new List<string>();
                var expected = new List<string>();
                foreach (JsonElement outcome in vector.GetProperty("outcomes").EnumerateArray())
                {
                    expected.Add(outcome.GetString());
                    got.Add(forge.FlipCoin().Outcome);
                }
                Check(
                    expected.SequenceEqual(got),
                    "coins seed " + seed,
                    string.Join(",", expected),
                    string.Join(",", got));
            }
        }

        /// <summary>
        /// Structural equality, ignoring key order. Numbers are compared as
        /// doubles: every value in play is a whole number well inside a double,
        /// so equality is exact.
        /// </summary>
        private static bool DeepEqual(JsonElement a, JsonElement b)
        {
            if (a.ValueKind != b.ValueKind) return false;
            switch (a.ValueKind)
            {
                case JsonValueKind.Object:
                    var aProps = a.EnumerateObject().ToDictionary(p => p.Name, p => p.Value);
                    var bProps = b.EnumerateObject().ToDictionary(p => p.Name, p => p.Value);
                    if (aProps.Count != bProps.Count) return false;
                    foreach (var pair in aProps)
                    {
                        if (!bProps.TryGetValue(pair.Key, out JsonElement other)) return false;
                        if (!DeepEqual(pair.Value, other)) return false;
                    }
                    return true;
                case JsonValueKind.Array:
                    if (a.GetArrayLength() != b.GetArrayLength()) return false;
                    var aItems = a.EnumerateArray().ToList();
                    var bItems = b.EnumerateArray().ToList();
                    for (int index = 0; index < aItems.Count; index++)
                    {
                        if (!DeepEqual(aItems[index], bItems[index])) return false;
                    }
                    return true;
                case JsonValueKind.Number:
                    return a.GetDouble() == b.GetDouble();
                case JsonValueKind.String:
                    return a.GetString() == b.GetString();
                default:
                    return true; // true, false and null match on ValueKind alone
            }
        }
    }
}
