"""Emits the renderer's face-rotation tables from the generated manifest.

Run from the repository root after `build_dice.py`:

    python tools/blender/emit_rotations.py

Writes `packages/renderer-web/src/forge-rotations.ts`. Keeping the tables in
source rather than fetching the JSON at runtime means the theme costs no extra
request and stays type-checked; `forge-rotations.test.ts` compares the two so
they cannot drift.
"""

from __future__ import annotations

import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MANIFEST = os.path.join(REPO, "packages", "assets-forge", "forge", "face-rotations.json")
OUT = os.path.join(REPO, "packages", "renderer-web", "src", "forge-rotations.ts")

HEADER = """// biome-ignore-all lint/suspicious/noApproximativeNumericConstant: captured geometry, not math constants
// Generated by tools/blender/emit_rotations.py from the manifest in
// packages/assets-forge/. Do not edit by hand: rerun the generator.
//
// Entry `[value - 1]` is the quaternion (x, y, z, w) that orients the die so
// that value reads upward, already yawed so its numeral is the right way up.

import type { ShapedDieSides } from "./math/geometry.js";
import type { QuaternionTuple } from "./theme.js";

"""


def quaternion_literal(values) -> str:
    return "[" + ", ".join(f"{v:g}" for v in values) + "]"


def main() -> None:
    with open(MANIFEST) as handle:
        manifest = json.load(handle)

    lines = [HEADER]
    lines.append(
        "export const FORGE_FACE_ROTATIONS: Partial<\n"
        "  Record<ShapedDieSides, readonly QuaternionTuple[]>\n"
        "> = {\n"
    )
    for die, entry in manifest.items():
        if die == "coin":
            continue
        lines.append(f"  {die[1:]}: [\n")
        for quaternion in entry["rotations"]:
            lines.append(f"    {quaternion_literal(quaternion)},\n")
        lines.append("  ],\n")
    lines.append("};\n\n")

    coin = manifest["coin"]["rotations"]
    lines.append("/** Heads first, then tails. */\n")
    lines.append(
        "export const FORGE_COIN_ROTATIONS: readonly [QuaternionTuple, QuaternionTuple] = [\n"
    )
    for quaternion in coin:
        lines.append(f"  {quaternion_literal(quaternion)},\n")
    lines.append("];\n")

    with open(OUT, "w", newline="\n") as handle:
        handle.write("".join(lines))
    print(f"DICEFORGE_ROTATIONS_OK -> {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
