import { FORGE_COIN_ROTATIONS, FORGE_FACE_ROTATIONS } from "./forge-rotations.js";
import type { ShapedDieSides } from "./math/geometry.js";

/** Quaternion as [x, y, z, w]. */
export type QuaternionTuple = readonly [number, number, number, number];

/**
 * Optional 3D model set for a theme. Models are loaded lazily at presentation
 * time and are never bundled with the npm package; shapes without a model —
 * or without a complete face-rotation table — always fall back to the
 * built-in procedural dice so resolved outcomes stay trustworthy.
 */
export type DieModelSet = {
  /** glTF URL per die shape. */
  readonly urls: Partial<Record<ShapedDieSides, string>>;
  /**
   * Optional texture atlas per shape, applied to the loaded model's materials.
   * Lets one model serve every colour variant instead of shipping a model per
   * colour. A texture that fails to load leaves the model's own material alone.
   */
  readonly textureUrls?: Partial<Record<ShapedDieSides, string>>;
  /**
   * Texture for the tens half of a percentile pair, which reads 00-90 rather
   * than 0-9. Without one, both dice of a d100 use the plain d10 atlas.
   */
  readonly tensTextureUrl?: string;
  /**
   * Calibrated orientation table per shape: `faceRotations[shape][value - 1]`
   * rotates the normalized model so that face value points up (+Y). A model
   * is used only when its shape's table has exactly `shape` entries.
   */
  readonly faceRotations: Partial<Record<ShapedDieSides, readonly QuaternionTuple[]>>;
};

/** Optional 3D coin, whose two faces are textured independently. */
export type CoinModel = {
  readonly url: string;
  readonly textures?: {
    readonly heads?: string;
    readonly tails?: string;
    readonly rim?: string;
  };
  /** Heads first, then tails. */
  readonly rotations: readonly [QuaternionTuple, QuaternionTuple];
};

export type DiceTheme = {
  readonly name: string;
  /** Colors for procedural dice, the DOM fallback, and demo chrome. */
  readonly colors: { readonly die: string; readonly label: string };
  readonly models?: DieModelSet;
  readonly coin?: CoinModel;
};

/** True when `shape` may be presented with a theme model (URL + full table). */
export function hasCalibratedModel(
  models: DieModelSet | undefined,
  shape: ShapedDieSides,
): models is DieModelSet {
  return Boolean(models?.urls[shape] && models.faceRotations[shape]?.length === shape);
}

/** Colour variants of the first-party DiceForge die set (`assets/forge/`). */
export type ForgeColor = "ivory" | "red" | "blue" | "green" | "yellow";

export const FORGE_COLORS: readonly ForgeColor[] = ["ivory", "red", "blue", "green", "yellow"];

const FORGE_ACCENTS: Record<ForgeColor, { die: string; label: string }> = {
  ivory: { die: "#ece9df", label: "#20222a" },
  red: { die: "#a63c3c", label: "#f7ecec" },
  blue: { die: "#3c5aa6", label: "#ecf0f6" },
  green: { die: "#3c7a4c", label: "#ecf4ee" },
  yellow: { die: "#b9862e", label: "#faf4e8" },
};

const FORGE_SHAPES: readonly ShapedDieSides[] = [4, 6, 8, 10, 12, 20];

/**
 * The first-party die set: every shape the SDK resolves, including the d10 and
 * d12 no third-party pack here provides. Models are generated by
 * `tools/blender/build_dice.py` and their rotation tables are exact by
 * construction rather than calibrated (ADR-0011).
 *
 * `baseUrl` points at wherever `assets/forge/` is served from.
 */
export function forgeTheme(options: { baseUrl: string; color?: ForgeColor }): DiceTheme {
  const color = options.color ?? "ivory";
  const base = options.baseUrl.replace(/\/+$/, "");
  const urls: Partial<Record<ShapedDieSides, string>> = {};
  const textureUrls: Partial<Record<ShapedDieSides, string>> = {};
  for (const shape of FORGE_SHAPES) {
    urls[shape] = `${base}/d${shape}.glb`;
    textureUrls[shape] = `${base}/textures/${color}/d${shape}.png`;
  }
  const textureBase = `${base}/textures/${color}`;
  return {
    name: `forge-${color}`,
    colors: FORGE_ACCENTS[color],
    models: {
      urls,
      textureUrls,
      tensTextureUrl: `${base}/textures/${color}/d10_tens.png`,
      faceRotations: FORGE_FACE_ROTATIONS,
    },
    coin: {
      url: `${base}/coin.glb`,
      textures: {
        heads: `${textureBase}/coin_heads.png`,
        tails: `${textureBase}/coin_tails.png`,
        rim: `${textureBase}/coin_rim.png`,
      },
      rotations: FORGE_COIN_ROTATIONS,
    },
  };
}

export type KayKitColor = "red" | "blue" | "green" | "yellow";

export const KAYKIT_COLORS: readonly KayKitColor[] = ["red", "blue", "green", "yellow"];

/**
 * d6 face style in the KayKit pack: `numerals` uses the printed-number die,
 * `pips-a` and `pips-b` use the two modeled-pip dice. Only the d6 has styles;
 * every other shape is unaffected.
 */
export type KayKitD6Style = "numerals" | "pips-a" | "pips-b";

const KAYKIT_D6_FILE: Record<KayKitD6Style, string> = {
  numerals: "D6_C",
  "pips-a": "D6_A",
  "pips-b": "D6_B",
};

const KAYKIT_ACCENTS: Record<KayKitColor, { die: string; label: string }> = {
  red: { die: "#a63c3c", label: "#f6ecec" },
  blue: { die: "#3c5aa6", label: "#ecf0f6" },
  green: { die: "#3c7a4c", label: "#ecf4ee" },
  yellow: { die: "#b9862e", label: "#f9f3e6" },
};

/** Quarter-turn quaternion component. */
const Q = Math.SQRT1_2;

/**
 * Face-up rotation tables for the KayKit Board Game Bits dice (CC0, Kay
 * Lousberg), calibrated against the normalized models: entry `value - 1`
 * orients the die so that value reads upward. All colors share geometry, so
 * one table serves every color. See assets/LICENSES.md.
 *
 * Regenerate with the maintainer tool at examples/web-demo/calibrate.html
 * (`?shape=20&verify=1` re-renders straight from this table to prove it).
 */
export const KAYKIT_FACE_ROTATIONS: Partial<Record<ShapedDieSides, readonly QuaternionTuple[]>> = {
  4: [
    [0, 1, 0, 0],
    [0.816497, 0, 0, -0.57735],
    [0.816497, -0.5, 0, 0.288675],
    [0.816497, 0.5, 0, 0.288675],
  ],
  // The cube's rotations are exact quarter and half turns, so its components are
  // ±1/√2 rather than captured decimals. Faces 2-4 carry an extra half turn
  // about Y so their numerals read upright.
  6: [
    [-Q, 0, 0, Q],
    [-1, 0, 0, 0],
    [-Q, Q, 0, 0],
    [Q, Q, 0, 0],
    [0, 0, 0, 1],
    [Q, 0, 0, Q],
  ],
  8: [
    [-0.325058, 0, -0.325058, 0.888074],
    [-0.627963, 0, 0.627963, 0.459701],
    [-0.325058, 0, 0.325058, 0.888074],
    [-0.627963, 0, -0.627963, 0.459701],
    [0.325058, 0, 0.325058, 0.888074],
    [0.627963, 0, -0.627963, 0.459701],
    [0.325058, 0, -0.325058, 0.888074],
    [0.627963, 0, 0.627963, 0.459701],
  ],
  20: [
    [-0.770582, 0, 0, 0.637341],
    [0.623414, 0, -0.452937, 0.637341],
    [-0.25923, 0, 0.188342, 0.947274],
    [0.76636, 0, 0.556793, 0.320426],
    [-0.292724, 0, -0.900911, 0.320426],
    [0.196949, 0, 0.606147, 0.770582],
    [-0.51562, 0, -0.37462, 0.770582],
    [0.320426, 0, 0, 0.947274],
    [-0.238123, 0, 0.732867, 0.637341],
    [0.099017, 0, -0.304743, 0.947274],
    [-0.292724, 0, 0.900911, 0.320426],
    [0.196949, 0, -0.606147, 0.770582],
    [-0.947274, 0, 0, 0.320426],
    [0.623414, 0, 0.452937, 0.637341],
    [-0.238123, 0, -0.732867, 0.637341],
    [0.099017, 0, 0.304743, 0.947274],
    [-0.25923, 0, -0.188342, 0.947274],
    [0.76636, 0, -0.556794, 0.320426],
    [-0.51562, 0, 0.37462, 0.770582],
    [0.637341, 0, 0, 0.770582],
  ],
};

/**
 * The pip d6 models (`D6_A`, `D6_B`) carry their own face layout, so they need
 * a table of their own; the numeral die's does not transfer.
 */
export const KAYKIT_PIP_D6_ROTATIONS: readonly QuaternionTuple[] = [
  [0, 0, -1, 0],
  [0, 0, Q, Q],
  [-Q, 0, 0, Q],
  [Q, 0, 0, Q],
  [0, 0, -Q, Q],
  [0, 0, 0, 1],
];

/**
 * Built-in theme for the KayKit dice models (d4, d6, d8, d20; other shapes
 * render procedurally in the theme's colors). `baseUrl` is wherever the
 * assets directory is served from, e.g. "/": the files themselves stay out
 * of the npm package.
 */
export function kayKitTheme(options: {
  baseUrl: string;
  color?: KayKitColor;
  /** d6 face style; defaults to printed numerals. */
  d6Style?: KayKitD6Style;
}): DiceTheme {
  const color = options.color ?? "red";
  const d6Style = options.d6Style ?? "numerals";
  const base = options.baseUrl.replace(/\/+$/, "");
  return {
    name: d6Style === "numerals" ? `kaykit-${color}` : `kaykit-${color}-${d6Style}`,
    colors: KAYKIT_ACCENTS[color],
    models: {
      urls: {
        4: `${base}/D4_${color}.gltf`,
        6: `${base}/${KAYKIT_D6_FILE[d6Style]}_${color}.gltf`,
        8: `${base}/D8_${color}.gltf`,
        20: `${base}/D20_${color}.gltf`,
      },
      faceRotations:
        d6Style === "numerals"
          ? KAYKIT_FACE_ROTATIONS
          : { ...KAYKIT_FACE_ROTATIONS, 6: KAYKIT_PIP_D6_ROTATIONS },
    },
  };
}
