extends Node
## Runs the core conformance vectors against the GDScript port (ADR-0021).
##
## The vectors are generated by the TypeScript core and committed at
## packages/testing/vectors/core-vectors.json; this runner must reproduce every
## number, normalized string, error position and record in them, bit for bit.
## Exit code 0 when everything matches; failures print expected vs got.

const SeededRandom := preload("res://addons/diceforge/seeded_random.gd")
const Notation := preload("res://addons/diceforge/notation.gd")
const Forge := preload("res://addons/diceforge/dice_forge.gd")

var _failures := 0
var _checks := 0
var _report: Array[String] = []


func _ready() -> void:
	var vectors := _load_vectors()
	if vectors.is_empty():
		var out := FileAccess.open(
			ProjectSettings.globalize_path("res://").path_join("conformance-report.txt"),
			FileAccess.WRITE,
		)
		if out != null:
			out.store_string("CONFORMANCE FAIL: vectors could not be loaded
")
		get_tree().quit(1)
		return
	_run_rng(vectors["rng"])
	_run_faces(vectors["faces"])
	_run_parse(vectors["parse"], vectors["rolls"])
	_run_parse_errors(vectors["parseErrors"], vectors["rolls"])
	_run_rolls(vectors["rolls"])
	_run_coins(vectors["coins"])
	var summary := "CONFORMANCE %s: %d checks, %d failures" % [
		"PASS" if _failures == 0 else "FAIL", _checks, _failures
	]
	print(summary)
	_report.append(summary)
	# The process quits as soon as the run ends, taking stdout with it when a
	# harness launched it — so the report also lands beside the project.
	var out := FileAccess.open(
		ProjectSettings.globalize_path("res://").path_join("conformance-report.txt"),
		FileAccess.WRITE,
	)
	if out != null:
		out.store_string("
".join(_report) + "
")
	get_tree().quit(0 if _failures == 0 else 1)


func _load_vectors() -> Dictionary:
	var path := ProjectSettings.globalize_path("res://").path_join(
		"../../packages/testing/vectors/core-vectors.json"
	)
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		printerr("cannot open vectors at %s" % path)
		return {}
	var parsed = JSON.parse_string(file.get_as_text())
	if parsed == null or not parsed is Dictionary:
		printerr("vectors did not parse as a JSON object")
		return {}
	return parsed


## The fate registry the vectors were generated with, wherever a vector
## declares custom dice.
func _registry_of(roll_vector: Dictionary) -> Dictionary:
	var registry := {}
	for definition in roll_vector.get("dice", []):
		registry[String(definition["id"]).to_lower()] = definition
	return registry


func _check(ok: bool, label: String, expected, got) -> void:
	_checks += 1
	if ok:
		return
	_failures += 1
	printerr("FAIL %s" % label)
	printerr("  expected: %s" % JSON.stringify(expected))
	printerr("  got:      %s" % JSON.stringify(got))
	_report.append("FAIL %s" % label)
	_report.append("  expected: %s" % JSON.stringify(expected))
	_report.append("  got:      %s" % JSON.stringify(got))


## JSON numbers arrive as floats; the port produces ints. Every value in play
## is a whole number well inside a double, so numeric equality is exact.
func _deep_equal(a, b) -> bool:
	var a_num := typeof(a) == TYPE_INT or typeof(a) == TYPE_FLOAT
	var b_num := typeof(b) == TYPE_INT or typeof(b) == TYPE_FLOAT
	if a_num and b_num:
		return float(a) == float(b)
	if typeof(a) != typeof(b):
		return false
	if a is Dictionary:
		if a.size() != b.size():
			return false
		for key in a:
			if not b.has(key) or not _deep_equal(a[key], b[key]):
				return false
		return true
	if a is Array:
		if a.size() != b.size():
			return false
		for index in a.size():
			if not _deep_equal(a[index], b[index]):
				return false
		return true
	return a == b


func _run_rng(vectors: Array) -> void:
	for vector in vectors:
		var source := SeededRandom.create(vector["seed"])
		var got: Array = []
		for i in vector["uint32"].size():
			got.append(source.next_uint32())
		_check(_deep_equal(vector["uint32"], got), "rng seed %s" % vector["seed"], vector["uint32"], got)


func _run_faces(vectors: Array) -> void:
	for vector in vectors:
		var forge := Forge.seeded(vector["seed"])
		var got: Array = []
		for i in vector["values"].size():
			var record = forge.roll("1d%d" % int(vector["sides"]))
			got.append(record["groups"][0]["dice"][0]["value"])
		_check(
			_deep_equal(vector["values"], got),
			"faces seed %s d%d" % [vector["seed"], int(vector["sides"])],
			vector["values"],
			got,
		)


## Every parse vector runs against the registry the generator used: the fate
## die from the roll vectors, which is the only one the vectors define.
func _fate_registry(rolls: Array) -> Dictionary:
	for roll_vector in rolls:
		if roll_vector.has("dice"):
			return _registry_of(roll_vector)
	return {}


func _run_parse(vectors: Array, rolls: Array) -> void:
	var registry := _fate_registry(rolls)
	for vector in vectors:
		var parsed := Notation.parse(vector["expression"], registry, true)
		var got = parsed["expr"]["normalized"] if parsed["ok"] else parsed
		_check(
			parsed["ok"] and got == vector["normalized"],
			'parse "%s"' % vector["expression"],
			vector["normalized"],
			got,
		)


func _run_parse_errors(vectors: Array, rolls: Array) -> void:
	var registry := _fate_registry(rolls)
	for vector in vectors:
		var parsed := Notation.parse(vector["expression"], registry, true)
		var got = "parsed fine" if parsed["ok"] else parsed["position"]
		_check(
			not parsed["ok"] and _deep_equal(parsed["position"], vector["position"]),
			'parse error "%s"' % vector["expression"],
			vector["position"],
			got,
		)


func _run_rolls(vectors: Array) -> void:
	for vector in vectors:
		var forge := Forge.seeded(vector["seed"])
		for definition in vector.get("dice", []):
			var faces: Array = []
			for face in definition["faces"]:
				var entry := {"value": int(face["value"])}
				if face.has("label"):
					entry["label"] = face["label"]
				faces.append(entry)
			forge.define_die(definition["id"], faces)
		var got = forge.roll(vector["expression"])
		_check(
			_deep_equal(vector["record"], got),
			'roll "%s" seed %s' % [vector["expression"], vector["seed"]],
			vector["record"],
			got,
		)


func _run_coins(vectors: Array) -> void:
	for vector in vectors:
		var forge := Forge.seeded(vector["seed"])
		var got: Array = []
		for i in vector["outcomes"].size():
			got.append(forge.flip_coin()["outcome"])
		_check(_deep_equal(vector["outcomes"], got), "coins seed %s" % vector["seed"], vector["outcomes"], got)
